//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
namespace ClasesBase
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class BDpasajesEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new BDpasajesEntities object using the connection string found in the 'BDpasajesEntities' section of the application configuration file.
        /// </summary>
        public BDpasajesEntities() : base("name=BDpasajesEntities", "BDpasajesEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new BDpasajesEntities object.
        /// </summary>
        public BDpasajesEntities(string connectionString) : base(connectionString, "BDpasajesEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new BDpasajesEntities object.
        /// </summary>
        public BDpasajesEntities(EntityConnection connection) : base(connection, "BDpasajesEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Autobus> Autobus
        {
            get
            {
                if ((_Autobus == null))
                {
                    _Autobus = base.CreateObjectSet<Autobus>("Autobus");
                }
                return _Autobus;
            }
        }
        private ObjectSet<Autobus> _Autobus;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Ciudad> Ciudad
        {
            get
            {
                if ((_Ciudad == null))
                {
                    _Ciudad = base.CreateObjectSet<Ciudad>("Ciudad");
                }
                return _Ciudad;
            }
        }
        private ObjectSet<Ciudad> _Ciudad;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Cliente> Cliente
        {
            get
            {
                if ((_Cliente == null))
                {
                    _Cliente = base.CreateObjectSet<Cliente>("Cliente");
                }
                return _Cliente;
            }
        }
        private ObjectSet<Cliente> _Cliente;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Pasaje> Pasaje
        {
            get
            {
                if ((_Pasaje == null))
                {
                    _Pasaje = base.CreateObjectSet<Pasaje>("Pasaje");
                }
                return _Pasaje;
            }
        }
        private ObjectSet<Pasaje> _Pasaje;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Rol> Rol
        {
            get
            {
                if ((_Rol == null))
                {
                    _Rol = base.CreateObjectSet<Rol>("Rol");
                }
                return _Rol;
            }
        }
        private ObjectSet<Rol> _Rol;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Servicio> Servicio
        {
            get
            {
                if ((_Servicio == null))
                {
                    _Servicio = base.CreateObjectSet<Servicio>("Servicio");
                }
                return _Servicio;
            }
        }
        private ObjectSet<Servicio> _Servicio;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Terminal> Terminal
        {
            get
            {
                if ((_Terminal == null))
                {
                    _Terminal = base.CreateObjectSet<Terminal>("Terminal");
                }
                return _Terminal;
            }
        }
        private ObjectSet<Terminal> _Terminal;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Usuario> Usuario
        {
            get
            {
                if ((_Usuario == null))
                {
                    _Usuario = base.CreateObjectSet<Usuario>("Usuario");
                }
                return _Usuario;
            }
        }
        private ObjectSet<Usuario> _Usuario;

        #endregion

        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Autobus EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToAutobus(Autobus autobus)
        {
            base.AddObject("Autobus", autobus);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Ciudad EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToCiudad(Ciudad ciudad)
        {
            base.AddObject("Ciudad", ciudad);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Cliente EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToCliente(Cliente cliente)
        {
            base.AddObject("Cliente", cliente);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Pasaje EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToPasaje(Pasaje pasaje)
        {
            base.AddObject("Pasaje", pasaje);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Rol EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToRol(Rol rol)
        {
            base.AddObject("Rol", rol);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Servicio EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToServicio(Servicio servicio)
        {
            base.AddObject("Servicio", servicio);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Terminal EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToTerminal(Terminal terminal)
        {
            base.AddObject("Terminal", terminal);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Usuario EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToUsuario(Usuario usuario)
        {
            base.AddObject("Usuario", usuario);
        }

        #endregion

    }

    #endregion

    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="BDpasajesModel", Name="Autobus")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Autobus : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Autobus object.
        /// </summary>
        /// <param name="aut_codigo">Initial value of the aut_codigo property.</param>
        public static Autobus CreateAutobus(global::System.Int32 aut_codigo)
        {
            Autobus autobus = new Autobus();
            autobus.aut_codigo = aut_codigo;
            return autobus;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 aut_codigo
        {
            get
            {
                return _aut_codigo;
            }
            set
            {
                if (_aut_codigo != value)
                {
                    Onaut_codigoChanging(value);
                    ReportPropertyChanging("aut_codigo");
                    _aut_codigo = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("aut_codigo");
                    Onaut_codigoChanged();
                }
            }
        }
        private global::System.Int32 _aut_codigo;
        partial void Onaut_codigoChanging(global::System.Int32 value);
        partial void Onaut_codigoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> aut_capacidad
        {
            get
            {
                return _aut_capacidad;
            }
            set
            {
                Onaut_capacidadChanging(value);
                ReportPropertyChanging("aut_capacidad");
                _aut_capacidad = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("aut_capacidad");
                Onaut_capacidadChanged();
            }
        }
        private Nullable<global::System.Int32> _aut_capacidad;
        partial void Onaut_capacidadChanging(Nullable<global::System.Int32> value);
        partial void Onaut_capacidadChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String aut_tiposervicio
        {
            get
            {
                return _aut_tiposervicio;
            }
            set
            {
                Onaut_tiposervicioChanging(value);
                ReportPropertyChanging("aut_tiposervicio");
                _aut_tiposervicio = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("aut_tiposervicio");
                Onaut_tiposervicioChanged();
            }
        }
        private global::System.String _aut_tiposervicio;
        partial void Onaut_tiposervicioChanging(global::System.String value);
        partial void Onaut_tiposervicioChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String aut_matricula
        {
            get
            {
                return _aut_matricula;
            }
            set
            {
                Onaut_matriculaChanging(value);
                ReportPropertyChanging("aut_matricula");
                _aut_matricula = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("aut_matricula");
                Onaut_matriculaChanged();
            }
        }
        private global::System.String _aut_matricula;
        partial void Onaut_matriculaChanging(global::System.String value);
        partial void Onaut_matriculaChanged();

        #endregion

    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="BDpasajesModel", Name="Ciudad")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Ciudad : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Ciudad object.
        /// </summary>
        /// <param name="ciu_codigo">Initial value of the ciu_codigo property.</param>
        public static Ciudad CreateCiudad(global::System.Int32 ciu_codigo)
        {
            Ciudad ciudad = new Ciudad();
            ciudad.ciu_codigo = ciu_codigo;
            return ciudad;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ciu_codigo
        {
            get
            {
                return _ciu_codigo;
            }
            set
            {
                if (_ciu_codigo != value)
                {
                    Onciu_codigoChanging(value);
                    ReportPropertyChanging("ciu_codigo");
                    _ciu_codigo = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ciu_codigo");
                    Onciu_codigoChanged();
                }
            }
        }
        private global::System.Int32 _ciu_codigo;
        partial void Onciu_codigoChanging(global::System.Int32 value);
        partial void Onciu_codigoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ciu_nombre
        {
            get
            {
                return _ciu_nombre;
            }
            set
            {
                Onciu_nombreChanging(value);
                ReportPropertyChanging("ciu_nombre");
                _ciu_nombre = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("ciu_nombre");
                Onciu_nombreChanged();
            }
        }
        private global::System.String _ciu_nombre;
        partial void Onciu_nombreChanging(global::System.String value);
        partial void Onciu_nombreChanged();

        #endregion

    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="BDpasajesModel", Name="Cliente")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Cliente : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Cliente object.
        /// </summary>
        /// <param name="cli_dni">Initial value of the cli_dni property.</param>
        public static Cliente CreateCliente(global::System.String cli_dni)
        {
            Cliente cliente = new Cliente();
            cliente.cli_dni = cli_dni;
            return cliente;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String cli_dni
        {
            get
            {
                return _cli_dni;
            }
            set
            {
                if (_cli_dni != value)
                {
                    Oncli_dniChanging(value);
                    ReportPropertyChanging("cli_dni");
                    _cli_dni = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("cli_dni");
                    Oncli_dniChanged();
                }
            }
        }
        private global::System.String _cli_dni;
        partial void Oncli_dniChanging(global::System.String value);
        partial void Oncli_dniChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String cli_nombre
        {
            get
            {
                return _cli_nombre;
            }
            set
            {
                Oncli_nombreChanging(value);
                ReportPropertyChanging("cli_nombre");
                _cli_nombre = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("cli_nombre");
                Oncli_nombreChanged();
            }
        }
        private global::System.String _cli_nombre;
        partial void Oncli_nombreChanging(global::System.String value);
        partial void Oncli_nombreChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String cli_apellido
        {
            get
            {
                return _cli_apellido;
            }
            set
            {
                Oncli_apellidoChanging(value);
                ReportPropertyChanging("cli_apellido");
                _cli_apellido = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("cli_apellido");
                Oncli_apellidoChanged();
            }
        }
        private global::System.String _cli_apellido;
        partial void Oncli_apellidoChanging(global::System.String value);
        partial void Oncli_apellidoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String cli_telefono
        {
            get
            {
                return _cli_telefono;
            }
            set
            {
                Oncli_telefonoChanging(value);
                ReportPropertyChanging("cli_telefono");
                _cli_telefono = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("cli_telefono");
                Oncli_telefonoChanged();
            }
        }
        private global::System.String _cli_telefono;
        partial void Oncli_telefonoChanging(global::System.String value);
        partial void Oncli_telefonoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String cli_email
        {
            get
            {
                return _cli_email;
            }
            set
            {
                Oncli_emailChanging(value);
                ReportPropertyChanging("cli_email");
                _cli_email = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("cli_email");
                Oncli_emailChanged();
            }
        }
        private global::System.String _cli_email;
        partial void Oncli_emailChanging(global::System.String value);
        partial void Oncli_emailChanged();

        #endregion

    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="BDpasajesModel", Name="Pasaje")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Pasaje : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Pasaje object.
        /// </summary>
        /// <param name="pas_codigo">Initial value of the pas_codigo property.</param>
        public static Pasaje CreatePasaje(global::System.Int32 pas_codigo)
        {
            Pasaje pasaje = new Pasaje();
            pasaje.pas_codigo = pas_codigo;
            return pasaje;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 pas_codigo
        {
            get
            {
                return _pas_codigo;
            }
            set
            {
                if (_pas_codigo != value)
                {
                    Onpas_codigoChanging(value);
                    ReportPropertyChanging("pas_codigo");
                    _pas_codigo = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("pas_codigo");
                    Onpas_codigoChanged();
                }
            }
        }
        private global::System.Int32 _pas_codigo;
        partial void Onpas_codigoChanging(global::System.Int32 value);
        partial void Onpas_codigoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String cli_dni
        {
            get
            {
                return _cli_dni;
            }
            set
            {
                Oncli_dniChanging(value);
                ReportPropertyChanging("cli_dni");
                _cli_dni = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("cli_dni");
                Oncli_dniChanged();
            }
        }
        private global::System.String _cli_dni;
        partial void Oncli_dniChanging(global::System.String value);
        partial void Oncli_dniChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> ser_codigo
        {
            get
            {
                return _ser_codigo;
            }
            set
            {
                Onser_codigoChanging(value);
                ReportPropertyChanging("ser_codigo");
                _ser_codigo = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ser_codigo");
                Onser_codigoChanged();
            }
        }
        private Nullable<global::System.Int32> _ser_codigo;
        partial void Onser_codigoChanging(Nullable<global::System.Int32> value);
        partial void Onser_codigoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> pas_asiento
        {
            get
            {
                return _pas_asiento;
            }
            set
            {
                Onpas_asientoChanging(value);
                ReportPropertyChanging("pas_asiento");
                _pas_asiento = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("pas_asiento");
                Onpas_asientoChanged();
            }
        }
        private Nullable<global::System.Int32> _pas_asiento;
        partial void Onpas_asientoChanging(Nullable<global::System.Int32> value);
        partial void Onpas_asientoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> pas_precio
        {
            get
            {
                return _pas_precio;
            }
            set
            {
                Onpas_precioChanging(value);
                ReportPropertyChanging("pas_precio");
                _pas_precio = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("pas_precio");
                Onpas_precioChanged();
            }
        }
        private Nullable<global::System.Decimal> _pas_precio;
        partial void Onpas_precioChanging(Nullable<global::System.Decimal> value);
        partial void Onpas_precioChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> pas_fechaHora
        {
            get
            {
                return _pas_fechaHora;
            }
            set
            {
                Onpas_fechaHoraChanging(value);
                ReportPropertyChanging("pas_fechaHora");
                _pas_fechaHora = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("pas_fechaHora");
                Onpas_fechaHoraChanged();
            }
        }
        private Nullable<global::System.DateTime> _pas_fechaHora;
        partial void Onpas_fechaHoraChanging(Nullable<global::System.DateTime> value);
        partial void Onpas_fechaHoraChanged();

        #endregion

    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="BDpasajesModel", Name="Rol")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Rol : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Rol object.
        /// </summary>
        /// <param name="rol_codigo">Initial value of the rol_codigo property.</param>
        public static Rol CreateRol(global::System.Int32 rol_codigo)
        {
            Rol rol = new Rol();
            rol.rol_codigo = rol_codigo;
            return rol;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 rol_codigo
        {
            get
            {
                return _rol_codigo;
            }
            set
            {
                if (_rol_codigo != value)
                {
                    Onrol_codigoChanging(value);
                    ReportPropertyChanging("rol_codigo");
                    _rol_codigo = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("rol_codigo");
                    Onrol_codigoChanged();
                }
            }
        }
        private global::System.Int32 _rol_codigo;
        partial void Onrol_codigoChanging(global::System.Int32 value);
        partial void Onrol_codigoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String rol_descripcion
        {
            get
            {
                return _rol_descripcion;
            }
            set
            {
                Onrol_descripcionChanging(value);
                ReportPropertyChanging("rol_descripcion");
                _rol_descripcion = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("rol_descripcion");
                Onrol_descripcionChanged();
            }
        }
        private global::System.String _rol_descripcion;
        partial void Onrol_descripcionChanging(global::System.String value);
        partial void Onrol_descripcionChanged();

        #endregion

    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="BDpasajesModel", Name="Servicio")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Servicio : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Servicio object.
        /// </summary>
        /// <param name="ser_codigo">Initial value of the ser_codigo property.</param>
        public static Servicio CreateServicio(global::System.Int32 ser_codigo)
        {
            Servicio servicio = new Servicio();
            servicio.ser_codigo = ser_codigo;
            return servicio;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ser_codigo
        {
            get
            {
                return _ser_codigo;
            }
            set
            {
                if (_ser_codigo != value)
                {
                    Onser_codigoChanging(value);
                    ReportPropertyChanging("ser_codigo");
                    _ser_codigo = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ser_codigo");
                    Onser_codigoChanged();
                }
            }
        }
        private global::System.Int32 _ser_codigo;
        partial void Onser_codigoChanging(global::System.Int32 value);
        partial void Onser_codigoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> aut_codigo
        {
            get
            {
                return _aut_codigo;
            }
            set
            {
                Onaut_codigoChanging(value);
                ReportPropertyChanging("aut_codigo");
                _aut_codigo = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("aut_codigo");
                Onaut_codigoChanged();
            }
        }
        private Nullable<global::System.Int32> _aut_codigo;
        partial void Onaut_codigoChanging(Nullable<global::System.Int32> value);
        partial void Onaut_codigoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> ser_fecha
        {
            get
            {
                return _ser_fecha;
            }
            set
            {
                Onser_fechaChanging(value);
                ReportPropertyChanging("ser_fecha");
                _ser_fecha = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ser_fecha");
                Onser_fechaChanged();
            }
        }
        private Nullable<global::System.DateTime> _ser_fecha;
        partial void Onser_fechaChanging(Nullable<global::System.DateTime> value);
        partial void Onser_fechaChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> ter_codigo_origen
        {
            get
            {
                return _ter_codigo_origen;
            }
            set
            {
                Onter_codigo_origenChanging(value);
                ReportPropertyChanging("ter_codigo_origen");
                _ter_codigo_origen = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ter_codigo_origen");
                Onter_codigo_origenChanged();
            }
        }
        private Nullable<global::System.Int32> _ter_codigo_origen;
        partial void Onter_codigo_origenChanging(Nullable<global::System.Int32> value);
        partial void Onter_codigo_origenChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> ter_codigo_destino
        {
            get
            {
                return _ter_codigo_destino;
            }
            set
            {
                Onter_codigo_destinoChanging(value);
                ReportPropertyChanging("ter_codigo_destino");
                _ter_codigo_destino = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ter_codigo_destino");
                Onter_codigo_destinoChanged();
            }
        }
        private Nullable<global::System.Int32> _ter_codigo_destino;
        partial void Onter_codigo_destinoChanging(Nullable<global::System.Int32> value);
        partial void Onter_codigo_destinoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ser_estado
        {
            get
            {
                return _ser_estado;
            }
            set
            {
                Onser_estadoChanging(value);
                ReportPropertyChanging("ser_estado");
                _ser_estado = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("ser_estado");
                Onser_estadoChanged();
            }
        }
        private global::System.String _ser_estado;
        partial void Onser_estadoChanging(global::System.String value);
        partial void Onser_estadoChanged();

        #endregion

    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="BDpasajesModel", Name="Terminal")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Terminal : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Terminal object.
        /// </summary>
        /// <param name="ter_codigo">Initial value of the ter_codigo property.</param>
        public static Terminal CreateTerminal(global::System.Int32 ter_codigo)
        {
            Terminal terminal = new Terminal();
            terminal.ter_codigo = ter_codigo;
            return terminal;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ter_codigo
        {
            get
            {
                return _ter_codigo;
            }
            set
            {
                if (_ter_codigo != value)
                {
                    Onter_codigoChanging(value);
                    ReportPropertyChanging("ter_codigo");
                    _ter_codigo = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ter_codigo");
                    Onter_codigoChanged();
                }
            }
        }
        private global::System.Int32 _ter_codigo;
        partial void Onter_codigoChanging(global::System.Int32 value);
        partial void Onter_codigoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> ciu_codigo
        {
            get
            {
                return _ciu_codigo;
            }
            set
            {
                Onciu_codigoChanging(value);
                ReportPropertyChanging("ciu_codigo");
                _ciu_codigo = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ciu_codigo");
                Onciu_codigoChanged();
            }
        }
        private Nullable<global::System.Int32> _ciu_codigo;
        partial void Onciu_codigoChanging(Nullable<global::System.Int32> value);
        partial void Onciu_codigoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ter_nombre
        {
            get
            {
                return _ter_nombre;
            }
            set
            {
                Onter_nombreChanging(value);
                ReportPropertyChanging("ter_nombre");
                _ter_nombre = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("ter_nombre");
                Onter_nombreChanged();
            }
        }
        private global::System.String _ter_nombre;
        partial void Onter_nombreChanging(global::System.String value);
        partial void Onter_nombreChanged();

        #endregion

    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="BDpasajesModel", Name="Usuario")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Usuario : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Usuario object.
        /// </summary>
        /// <param name="usu_id">Initial value of the usu_id property.</param>
        public static Usuario CreateUsuario(global::System.Int32 usu_id)
        {
            Usuario usuario = new Usuario();
            usuario.usu_id = usu_id;
            return usuario;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 usu_id
        {
            get
            {
                return _usu_id;
            }
            set
            {
                if (_usu_id != value)
                {
                    Onusu_idChanging(value);
                    ReportPropertyChanging("usu_id");
                    _usu_id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("usu_id");
                    Onusu_idChanged();
                }
            }
        }
        private global::System.Int32 _usu_id;
        partial void Onusu_idChanging(global::System.Int32 value);
        partial void Onusu_idChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String usu_nombreUsuario
        {
            get
            {
                return _usu_nombreUsuario;
            }
            set
            {
                Onusu_nombreUsuarioChanging(value);
                ReportPropertyChanging("usu_nombreUsuario");
                _usu_nombreUsuario = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("usu_nombreUsuario");
                Onusu_nombreUsuarioChanged();
            }
        }
        private global::System.String _usu_nombreUsuario;
        partial void Onusu_nombreUsuarioChanging(global::System.String value);
        partial void Onusu_nombreUsuarioChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String usu_apellidoNombre
        {
            get
            {
                return _usu_apellidoNombre;
            }
            set
            {
                Onusu_apellidoNombreChanging(value);
                ReportPropertyChanging("usu_apellidoNombre");
                _usu_apellidoNombre = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("usu_apellidoNombre");
                Onusu_apellidoNombreChanged();
            }
        }
        private global::System.String _usu_apellidoNombre;
        partial void Onusu_apellidoNombreChanging(global::System.String value);
        partial void Onusu_apellidoNombreChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String usu_contraseña
        {
            get
            {
                return _usu_contraseña;
            }
            set
            {
                Onusu_contraseñaChanging(value);
                ReportPropertyChanging("usu_contraseña");
                _usu_contraseña = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("usu_contraseña");
                Onusu_contraseñaChanged();
            }
        }
        private global::System.String _usu_contraseña;
        partial void Onusu_contraseñaChanging(global::System.String value);
        partial void Onusu_contraseñaChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> rol_codigo
        {
            get
            {
                return _rol_codigo;
            }
            set
            {
                Onrol_codigoChanging(value);
                ReportPropertyChanging("rol_codigo");
                _rol_codigo = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("rol_codigo");
                Onrol_codigoChanged();
            }
        }
        private Nullable<global::System.Int32> _rol_codigo;
        partial void Onrol_codigoChanging(Nullable<global::System.Int32> value);
        partial void Onrol_codigoChanged();

        #endregion

    
    }

    #endregion

    
}
